development:
  adapter: postgresql
  encoding: utf8
  database: addresslist_development
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: addresslist_test
  username: postgres
  password: postgres
  host: localhost